#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/Users/cwillis/dev/mrc/gwt-2.3.0/gwt-user.jar:/Users/cwillis/dev/mrc/gwt-2.3.0/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src org.unc.hive.client.HIVEMessages -createMessages ;

